server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # HTML y SPA Fallback: NUNCA guardar en caché index.html para refrescar deployments inmediatamente
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    # Archivos estáticos de Vite (/assets/)
    location /assets/ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }
}
